# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thiago/repositorios/mac0448-ep4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thiago/repositorios/mac0448-ep4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thiago/repositorios/mac0448-ep4/CMakeFiles /home/thiago/repositorios/mac0448-ep4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thiago/repositorios/mac0448-ep4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ep4

# Build rule for target.
ep4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ep4
.PHONY : ep4

# fast build rule for target.
ep4/fast:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/build
.PHONY : ep4/fast

src/ep4.o: src/ep4.cxx.o
.PHONY : src/ep4.o

# target to build an object file
src/ep4.cxx.o:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/ep4.cxx.o
.PHONY : src/ep4.cxx.o

src/ep4.i: src/ep4.cxx.i
.PHONY : src/ep4.i

# target to preprocess a source file
src/ep4.cxx.i:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/ep4.cxx.i
.PHONY : src/ep4.cxx.i

src/ep4.s: src/ep4.cxx.s
.PHONY : src/ep4.s

# target to generate assembly for a file
src/ep4.cxx.s:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/ep4.cxx.s
.PHONY : src/ep4.cxx.s

src/main.o: src/main.cxx.o
.PHONY : src/main.o

# target to build an object file
src/main.cxx.o:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/main.cxx.o
.PHONY : src/main.cxx.o

src/main.i: src/main.cxx.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cxx.i:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/main.cxx.i
.PHONY : src/main.cxx.i

src/main.s: src/main.cxx.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cxx.s:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/main.cxx.s
.PHONY : src/main.cxx.s

src/network.o: src/network.cxx.o
.PHONY : src/network.o

# target to build an object file
src/network.cxx.o:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/network.cxx.o
.PHONY : src/network.cxx.o

src/network.i: src/network.cxx.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.cxx.i:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/network.cxx.i
.PHONY : src/network.cxx.i

src/network.s: src/network.cxx.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.cxx.s:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/network.cxx.s
.PHONY : src/network.cxx.s

src/packet.o: src/packet.cxx.o
.PHONY : src/packet.o

# target to build an object file
src/packet.cxx.o:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/packet.cxx.o
.PHONY : src/packet.cxx.o

src/packet.i: src/packet.cxx.i
.PHONY : src/packet.i

# target to preprocess a source file
src/packet.cxx.i:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/packet.cxx.i
.PHONY : src/packet.cxx.i

src/packet.s: src/packet.cxx.s
.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.cxx.s:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/packet.cxx.s
.PHONY : src/packet.cxx.s

src/router.o: src/router.cxx.o
.PHONY : src/router.o

# target to build an object file
src/router.cxx.o:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/router.cxx.o
.PHONY : src/router.cxx.o

src/router.i: src/router.cxx.i
.PHONY : src/router.i

# target to preprocess a source file
src/router.cxx.i:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/router.cxx.i
.PHONY : src/router.cxx.i

src/router.s: src/router.cxx.s
.PHONY : src/router.s

# target to generate assembly for a file
src/router.cxx.s:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/router.cxx.s
.PHONY : src/router.cxx.s

src/transmissionqueue.o: src/transmissionqueue.cxx.o
.PHONY : src/transmissionqueue.o

# target to build an object file
src/transmissionqueue.cxx.o:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/transmissionqueue.cxx.o
.PHONY : src/transmissionqueue.cxx.o

src/transmissionqueue.i: src/transmissionqueue.cxx.i
.PHONY : src/transmissionqueue.i

# target to preprocess a source file
src/transmissionqueue.cxx.i:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/transmissionqueue.cxx.i
.PHONY : src/transmissionqueue.cxx.i

src/transmissionqueue.s: src/transmissionqueue.cxx.s
.PHONY : src/transmissionqueue.s

# target to generate assembly for a file
src/transmissionqueue.cxx.s:
	$(MAKE) -f CMakeFiles/ep4.dir/build.make CMakeFiles/ep4.dir/src/transmissionqueue.cxx.s
.PHONY : src/transmissionqueue.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ep4"
	@echo "... rebuild_cache"
	@echo "... src/ep4.o"
	@echo "... src/ep4.i"
	@echo "... src/ep4.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/router.o"
	@echo "... src/router.i"
	@echo "... src/router.s"
	@echo "... src/transmissionqueue.o"
	@echo "... src/transmissionqueue.i"
	@echo "... src/transmissionqueue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

